pessimistic v3
Cheelee-inc/smartcontracts pull request #7
Opened 2022-12-14 09:02 UTC by rs-Nenad

2022-12-14 11:13 UTC, sviatoslav-alekseev approved these changes

2022-12-14 11:14 UTC, dragvs requested changes

2022-12-14 11:14 UTC, dragvs commented on contracts/MultiVesting.sol
> +        beneficiary[it.newBeneficiary] = beneficiary[it.oldBeneficiary];
Проблема - можем перетереть существующий вестинг

2022-12-14 11:14 UTC, dragvs commented on contracts/MultiVesting.sol
> +        beneficiary[it.newBeneficiary] = beneficiary[it.oldBeneficiary];
Стоит ли нам очистить update lock в таком случае?

2022-12-14 11:14 UTC, dragvs commented on contracts/MultiVesting.sol
> +        updateBeneficiaryLock[msg.sender] = UpdateBeneficiaryLock(_oldBeneficiary, _newBeneficiary, block.timestamp + DELTA_TIME);
Нам нужен срок дедлайна до которого необходимо вызвать `finishUpdate...`, после него `update` становится невалидным

2022-12-14 11:14 UTC, dragvs commented on contracts/MultiVesting.sol
> +    uint256 immutable DELTA_TIME;
Помимо этого нам еще нужен макс срок смены бенефициара (deadline)

2022-12-16 08:32 UTC, sviatoslav-alekseev approved these changes

2022-12-16 12:40 UTC, dragvs approved these changes

2022-12-16 15:15 UTC, merged